Documentation Update: Campaigns
xlink-network/xlink-docs pull request #2
Opened 2024-10-10 18:36 UTC by ignaciopenia

This PR impacts on [docs.xlink.network](https://docs.xlink.network/). The changes can be previewed at the temporary URL [here](https://coinfabrik.gitbook.io/xlink-docs/getting-started/the-bridge).

A new section was created within **Getting Started** guide called **Campaigns**. It offers instructions and examples for users interested in participating in XLink campaigns. Below are the main changes performed:

- Added a introduction explaining what campaigns are and how to participate.
- Added the steps for participating in campaigns, including how to navigate to the Campaigns tab in the XLink app, register for a campaign and complete required actions (e.g., staking, adding liquidity).

2024-10-17 00:11 UTC, tenuki requested changes

2024-10-17 00:11 UTC, tenuki commented on getting-started/campaigns.md
> +description: Learn how to participate in XLink campaigns and earn rewards.
que te parece: 
 ->  Learn **what are and** how to participate in XLink campaigns and earn rewards.
?

2024-10-17 00:11 UTC, tenuki commented on getting-started/campaigns.md
> +Welcome to the **Campaigns**! XLink campaigns are special events where users can participate in various actions on supported blockchains to earn rewards. These actions typically involve interacting w
These actions typically involve interacting with **many different actors in the STACKS ecosystem, like** the XLink bridge, ~~such as staking tokens, adding liquidity, or bridging assets between chains.~~ **and use them to accomplish different challenges.**

2024-10-17 00:11 UTC, tenuki commented on getting-started/campaigns.md
> +Each campaign may have different requirements and actions to complete, but they all aim to incentivize user participation and enhance Bitcoin DeFi ecosystems. Below, we'll explore the rewards you can
que tal: 
"Each campaign ~~may have~~ **involves** different requirements and actions ~~to complete, but they~~ **, and** all aim to incentivize user participation and strengthen user confidence in the Bitcoin DeFi ecosystem"
?

2024-10-17 00:11 UTC, tenuki commented on getting-started/campaigns.md
> +Each campaign may have different requirements and actions to complete, but they all aim to incentivize user participation and enhance Bitcoin DeFi ecosystems. Below, we'll explore the rewards you can
"Below, we'll explore the rewards you can earn and some tips on how to maximize your participation."
-> maximize your participation or the earnings?

2024-10-17 00:11 UTC, tenuki commented on getting-started/campaigns.md
> +![Campaign Registration](../.gitbook/assets/campaigns/campaigns-menu.png)
Esta imagen mas que Registration parece Selection/Browsing/Navigation alguna de esas no?

2024-10-17 00:11 UTC, tenuki commented on getting-started/campaigns.md
> +For example, in the **ALEX Liquidity Campaign**, you’ll be directed to add liquidity on a supported DeFi platform. Be sure to follow the specific steps outlined in each campaign.
No habria que usar de vuelta  For example..   podriamos cambiar por: 
"**Similarly,** in the **ALEX Liquidity Campaign**, you’ll be directed to add liquidity on a supported DeFi platform. Be sure to follow the specific steps outlined in each campaign."

2024-10-17 17:53 UTC, ignaciopenia commented on getting-started/campaigns.md
> +Each campaign may have different requirements and actions to complete, but they all aim to incentivize user participation and enhance Bitcoin DeFi ecosystems. Below, we'll explore the rewards you can
I meant to take advantage of the participation opportunities that exist. But it is also related to getting more rewards..

2024-10-17 17:54 UTC, ignaciopenia commented on getting-started/campaigns.md
> +Each campaign may have different requirements and actions to complete, but they all aim to incentivize user participation and enhance Bitcoin DeFi ecosystems. Below, we'll explore the rewards you can
> "Below, we'll explore the rewards you can earn and some tips on how to maximize your participation." -> maximize your participation or the earnings?

I meant to take advantage of the participation opportunities that exist. But it is also related to getting more rewards..

2024-10-18 01:20 UTC, tenuki commented on getting-started/campaigns.md
> +Each campaign may have different requirements and actions to complete, but they all aim to incentivize user participation and enhance Bitcoin DeFi ecosystems. Below, we'll explore the rewards you can
good!

2024-10-18 01:21 UTC, tenuki approved these changes
all good

2024-10-19 08:54 UTC, merged