Developers: add xLINK contracts documentation (w1)
xlink-network/xlink-docs pull request #6
Opened 2024-12-06 19:07 UTC by ignaciopenia

## Description 

Added xLINK contract technical documents. Impacts on https://docs.xlink.network/. This branch is live at a temporary URL [here ](https://coinfabrik.gitbook.io/xlink-docs/xlink-contracts-w1).

### Changes

1. Created the Developers section (see Gitbook page groups).
2. Added technical documentation for the contracts:
    
    - `btc-peg-in-endpoint-v2-03.clar`
    - `meta-peg-in-endpoint-v2-02.clar`
    
3. Updated the `SUMMARY.md` accordingly. 

### Following work

- Continue with the contracts technical documentation as follows: `btc-peg-out-endpoint-v2-01.clar`, `meta-peg-out-endpoint-v2-03.clar`, `cross-peg-in-endpoint-v2-03.clar`, `cross-peg-out-endpoint-v2-01.clar`.

2024-12-12 22:19 UTC, tenuki requested changes
one minor change.!

2024-12-12 22:19 UTC, tenuki commented on developers/contracts/btc-peg-in-endpoint-v2-03.md
> +The percentage fee charged for peg-in transactions. By default, this value is u0.
here u0 must be `u0`

2024-12-18 00:08 UTC, tenuki requested changes
A minor change is required/requested.

2024-12-18 12:48 UTC, ignaciopenia commented on developers/contracts/btc-peg-in-endpoint-v2-03.md
> +The percentage fee charged for peg-in transactions. By default, this value is u0.
Done

2024-12-20 12:13 UTC, tenuki approved these changes

2024-12-20 16:21 UTC, merged