Developers: add xLINK contracts documentation (w3)
xlink-network/xlink-docs pull request #9
Opened 2024-12-27 13:25 UTC by ignaciopenia

## Description 

Added xLINK contract technical documents. Impacts on https://docs.xlink.network/. This branch is live at a temporary URL [here ](https://coinfabrik.gitbook.io/xlink-docs/xlink-contracts-w3).

### Changes

1. Added technical documentation for the contracts:
    
    - cross-peg-in-endpoint-v2-03.clar`
    - `cross-peg-out-endpoint-v2-01.clar`
    
2. Updated the `SUMMARY.md` accordingly. 

PLEASE FIRST MERGE PR https://github.com/xlink-network/xlink-docs/pull/7.

### Following work

- Index page and comprehensive overview for the technical documentation of contracts.
- Design refinements to accommodate the new sections on GitBook.

2025-01-09 20:30 UTC, tenuki requested changes

2025-01-09 20:30 UTC, tenuki commented on developers/contracts/cross-peg-in-endpoint-v2-03.md
> +| Map | `principal bool`|
Here I have two problems, one is general and the other is related to this doc.

1. general problem: I kind of disagree or don't fully understand the first column header "data".. and why here it is map instead of variable..  to me.. Map is part of the type...   cc: @sofinico ..
2. in particular in this case, @ignaciopenia , we should in some way express or make more explicit which is the key's type and which is the value's type.. maybe something like:  `principal → bool` or `Map: principal : bool`  or something?

2025-01-09 20:30 UTC, tenuki commented on developers/contracts/cross-peg-in-endpoint-v2-03.md
> +This function enables peg-in operations to transfer tokens from an external EVM-like blockchain to Stacks. It validates the provided order by checking its hash and verifying signatures to meet a thre
First it says: ".. from an external EVM-like blockchain to Stacks." and then it says: "..to route the tokens to the recipient on Stacks or another destination chain.".
One of them must be wrong..

2025-01-09 20:30 UTC, tenuki commented on developers/contracts/cross-peg-out-endpoint-v2-01.md
> +| Variable | `principal` `bool` |
I guess this should be a Map instead of a variable.. also check that I would add an arrow or something between `principal` and `bool`

2025-01-09 20:30 UTC, tenuki commented on developers/contracts/cross-peg-out-endpoint-v2-01.md
> +This map stores the whitelist status of users. Each entry associates a `principal` with a boolean value indicating whether they are authorized to perform peg-out transactions. If `true`, the user is
I think I would add: "**When `use-whitelist` if  this value is** `true`, the user is whitelisted; other..."  or something else..

As it is now, it seems that this applies always.. a comment about the `use-whitelist` to enable tihs is required here.

2025-01-09 22:26 UTC, ignaciopenia commented on developers/contracts/cross-peg-in-endpoint-v2-03.md
> +This function enables peg-in operations to transfer tokens from an external EVM-like blockchain to Stacks. It validates the provided order by checking its hash and verifying signatures to meet a thre
I'm revising this to make it clearer. What I meant to say is that with the cross-router, the route is established based on the `chain-id`. It determines whether the transaction goes directly to the Stacks network (if  `chain-id == None`) or is routed to another EVM-compatible blockchain (`chain-id < 1000`)

2025-01-10 13:02 UTC, tenuki approved these changes

2025-01-10 13:57 UTC, merged